# Site settings
author: Marc Mills
title: Corpus Callosum - Connecting Both Sides of My Brain
header-img: img/home-bg.png
email: mdmills1990@gmail.com
copyright_name: Marc Mills
description: > # this means to ignore newlines until "baseurl:"
  Corpus Callosum
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  musicmills1990

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
